name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/swiftcoderjoe/memeinator-homepage:latest
        
      - name: Publish the Docker image
        run: docker push ghcr.io/swiftcoderjoe/memeinator-homepage:latest